name: Deploy Frontend to S3 + CloudFront

on:
  push:
    branches: [ deploy-frontend ]
    paths:
      - 'myapp/frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync files to S3
        uses: aws-actions/s3-sync@v2
        with:
          bucket: ${{ secrets.S3_BUCKET }}
          region: ${{ secrets.AWS_REGION }}
          source-dir: myapp/frontend

      - name: Invalidate CloudFront cache
        uses: aws-actions/cloudfront-invalidate@v1
        with:
          distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          paths: "/*"

