services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: myapp_api
    expose:
      - "3000"

  nginx:
    image: nginx:stable
    container_name: myapp_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certbot/www:/var/www/certbot        # 👈 shared webroot
    depends_on:
      - api

  certbot:
    image: certbot/certbot
    container_name: myapp_certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certbot/www:/var/www/certbot        # 👈 shared webroot
    entrypoint: sh -c "trap exit TERM; while :; do sleep 1d; done"

volumes:
  certbot-etc:
  certbot-var:

